name: ${APP_NAME}

services:

  vite:
    build:
      context: .
      dockerfile: Dockerfile-vite
    container_name: ${APP_NAME}_vite
    volumes:
      - .:/app
      - /app/node_modules # exclude local mount
    command: npm run dev
    ports:
      - "5173:5173" # Vite default port, adjust if necessary
    networks:
      - livewire-network
    environment:
      - APP_URL=${APP_URL}

  phpfpm:
    build:
      dockerfile: Dockerfile
    container_name: ${APP_NAME}_phpfpm
    restart: unless-stopped
    tty: true
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_DATABASE}
    # working_dir: /var/www/html/
    volumes:
      - ./:/var/www/html/
      - ./.docker/phpfpm/php.ini:/usr/local/etc/php/conf.d/app.ini
    command: sh -c "php artisan migrate --force && php-fpm"
    networks:
      - livewire-network

  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: ${APP_NAME}_nginx
    restart: unless-stopped
    tty: true
    depends_on:
      - phpfpm
    ports:
      - "${PORT:-80}:80"
    volumes:
      - ./public:/var/www/html/public
      - ./.docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
    networks:
      - livewire-network

  postgres:
    build:
      context: ./.docker/db
    container_name: ${APP_NAME}_db
    ports:
      - "5432:5432"
    volumes:
      - pgsql:/var/lib/postgresql/data
    restart: unless-stopped
    tty: true
    environment:
      - PGPASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - livewire-network

#Docker Networks
networks:
  livewire-network:
    driver: bridge
#Volumes
volumes:
  pgsql :
